<a href="https://colab.research.google.com/github/vikkrock/Maths-for-ML-DL/blob/main/Working_with_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Importing Dependencies**

In [1]:
import numpy as np

### **Creating Matrix using Numpy**

In [3]:
matrix1=np.array([[2,3],[6,7]])
print(matrix1)

[[2 3]
 [6 7]]


In [4]:
matrix1.shape

(2, 2)

In [6]:
matrix2=np.array([[10,35,45],[50,64,80],[20,15,90]])

In [7]:
print(matrix2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [8]:
matrix2.shape

(3, 3)

### **Creating matrix with Random values**

In [11]:
random_mat=np.random.rand(3,3)
print(random_mat)

[[0.207136   0.17316865 0.08401454]
 [0.28009149 0.75636719 0.57194006]
 [0.32724352 0.32988079 0.55199114]]


In [12]:
# Creating matrix with random integer
random_mat=np.random.randint(100,size=(4,5))
print(random_mat)

[[43 88 61 29 41]
 [76 25 39 49 82]
 [84 89 47 39 93]
 [21 65  4 82  1]]


### **Matrix with all the values as 1**

In [14]:
matrix_3=np.ones((2,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [15]:
matrix_3=np.ones((9,5),dtype=int)
print(matrix_3)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### **Null Matrix or Zero Matrix**

In [19]:
null_mat=np.zeros(shape=(7,7),dtype=int)
print(null_mat)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


### **Identity Matrix**

In [22]:
identity_mat=np.eye(3,3,dtype=int)
print(identity_mat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### **Transpose of Matrix**

In [23]:
# matrix with Random integer values
a=np.random.randint(100,size=(4,5))
print(a)

[[72 85 73 13 90]
 [52 98 75  9 91]
 [98 74 48 99 17]
 [84 51 14 82 44]]


In [24]:
transpose_a=np.transpose(a)
print(transpose_a)

[[72 52 98 84]
 [85 98 74 51]
 [73 75 48 14]
 [13  9 99 82]
 [90 91 17 44]]


In [27]:
b=a.T
print(b)

[[72 52 98 84]
 [85 98 74 51]
 [73 75 48 14]
 [13  9 99 82]
 [90 91 17 44]]


### **Matrix Addition**
Two matrix that can be added only if they have same shape only

In [29]:
A=np.array([[2,5],[12,67]])
B=np.array([[3,54],[21,45]])
print(A)
print(B)

[[ 2  5]
 [12 67]]
[[ 3 54]
 [21 45]]


In [30]:
A.shape

(2, 2)

In [31]:
B.shape

(2, 2)

In [32]:
sum=A+B
print(sum)

[[  5  59]
 [ 33 112]]


In [33]:
# Creating two matrices with random values
mat_1=np.random.randint(10,size=(3,3))
mat_2=np.random.randint(20,size=(3,3))

In [34]:
print(mat_1)

[[0 3 2]
 [5 0 2]
 [3 0 7]]


In [35]:
print(mat_2)

[[17  5 11]
 [15  2 12]
 [15 18  0]]


In [36]:
sum=np.add(mat_1,mat_2)

In [37]:
print(sum)

[[17  8 13]
 [20  2 14]
 [18 18  7]]


In [38]:
mat_3=np.random.randint(10,size=(3,3))
mat_4=np.random.randint(20,size=(3,4))

In [40]:
sum=np.add(mat_3,mat_4)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

 **The above we can't get because the shape of the matrix is not same.**


## **Matrix Substraction**

In [41]:
mat_1=np.random.randint(10,size=(3,3))
mat_2=np.random.randint(20,size=(3,3))

In [42]:
subtract=mat_1-mat_2

In [43]:
print(subtract)

[[ -8 -10  -2]
 [  1   0 -15]
 [  4  -3  -4]]


In [44]:
diff=np.subtract(mat_1,mat_2)
print(diff)

[[ -8 -10  -2]
 [  1   0 -15]
 [  4  -3  -4]]


###**Multiplying a Matrix by a Scalar**

In [45]:
x=5
y=np.random.randint(15,size=(4,4))
mul=np.multiply(x,y)
print(mul)

[[20 25 40 70]
 [55 65 50  0]
 [70 20 65 40]
 [ 5 15 15 70]]


### **Multiplying 2 matrices**

In [47]:
# Create 2 matrices with random Values
mat_1=np.random.randint(10,size=(3,3))
mat_2=np.random.randint(20,size=(3,4))


In [48]:
print(mat_1)

[[0 3 6]
 [9 0 1]
 [7 2 7]]


In [49]:
print(mat_2)

[[ 1  4 15  6]
 [ 9  7  2  0]
 [ 9  1 11  7]]


In [50]:
multi=np.dot(mat_1,mat_2)

In [51]:
print(multi)

[[ 81  27  72  42]
 [ 18  37 146  61]
 [ 88  49 186  91]]


In [52]:
multi.shape

(3, 4)

In [53]:
pro=np.multiply(mat_1,mat_2) # not possible because it will multiply with same indexes so, shape must be equal

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 